# -*- coding: utf-8 -*-
"""dqn_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDwtc0qMUTAF_7w5Ey87QM4xR7Lc_AqD
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install baselines --no-deps

!python -m atari_py.import_roms /content/drive/MyDrive/game_ai/roms

from baselines.common.atari_wrappers import make_atari, wrap_deepmind
import numpy as np
import tensorflow as tf
from tensorflow import keras
import gym

seed = 42
model = keras.models.load_model("/content/drive/MyDrive/game_ai/model/model_{}0000.h5".format(80))

env = make_atari("BreakoutNoFrameskip-v4")
env = wrap_deepmind(env, frame_stack=True, scale=True)
env.seed(seed)

env = gym.wrappers.Monitor(env, '/content/drive/MyDrive/Videos', video_callable=lambda episode_id :True, force=True)

n_episodes = 10 
returns = []

for i in range(n_episodes): 
  ret=0
  
  state = np.array(env.reset())
  
  done = False

  while not done:
    state_tensor = tf.convert_to_tensor(state)
    state_tensor = tf.expand_dims(state_tensor, 0)
    action_values = model.predict(state_tensor)
    action = np.argmax(action_values)

    state_next, reward, done, _ = env.step(action)
    state = np.array(state_next)

    ret+=reward

  returns.append(ret)

env.close()
print("Returns: {}".format(returns))





